//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using StationCasinos.WebAPI.Utility;
using System.ComponentModel.DataAnnotations;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


public partial class EventRatingParimutuel : EventRating {
    
    private EObjectRatingParimutuel ratingField;

    [Required, ValidateObject]
    /// <remarks/>
    public EObjectRatingParimutuel Rating {
        get {
            return this.ratingField;
        }
        set {
            this.ratingField = value;
        }
    }
}

public partial class EObjectRatingParimutuel : EObjectRating {
    
    private EObjectRatingSessionParimutuel sessionField;
    
    private EObjectRatingActionParimutuel actionField;

    [Required, ValidateObject]
    /// <remarks/>
    public EObjectRatingSessionParimutuel Session {
        get {
            return this.sessionField;
        }
        set {
            this.sessionField = value;
        }
    }

    [Required, ValidateObject]
    /// <remarks/>
    public EObjectRatingActionParimutuel Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
}

public partial class EObjectRatingSessionParimutuel : EObjectRatingSession {
}

public partial class EObjectRatingActionParimutuel : EObjectRatingAction {
    
    private decimal parimutuelWonField;
    
    /// <remarks/>
    public decimal parimutuelWon {
        get {
            return this.parimutuelWonField;
        }
        set {
            this.parimutuelWonField = value;
        }
    }
}